### ISSUE TITLE
What does your plugin do?

### ISSUE THREAD

**Issue by ontargetWeb** [zero-24/plg_task_checkin#2]
Hi I'm looking for a checkin plugin that will auto checkin items - often users are editing from the frontend of joomla and are locked out and cannot checkin as they dont have backend access. Does your plugin help with this issue?
Thanks!

**Comment by zero-24** [comment]
yes it does and is intended to do that what you are asking for.

**Comment by zero-24** [comment]
Will close here now please feel free to open a new issue with specofic questions if there are any :⁠-⁠)
